//@prepros-append jquery-1.11.3.min.js
//@prepros-append jquery.easing.1.3.js  
//@prepros-append remodal.min.js
//@prepros-append jquery.validate.min.js 
//@prepros-append scrollIt.min.js
//@prepros-append plax.js  
//@prepros-append hammer.min.js
//@prepros-append toastr.js
//@prepros-append chromeSmoothScroll.min.js
//@prepros-append jquery.imgpreload.min.js  